baseURL = "https://hobofoto.netlify.app/"
languageCode = "ja-jp"
title = "HoBoFoTo"
theme = "github-style"
copyright = "Copyright Â© 2000-2020 Dr?Thomas All Rights Reserved."
defaultContentLanguage = "ja"
hasCJKLanguage = true

[params]
  author = "HoBoFoTo"
  description = "Hobo everyday foto."
  github = "drthomas246"
  facebook = "hobofoto.net"
  twitter = "hobofoto_net"
  email = "drthomas@hobofoto.net"
  avatar = "/17758220.png"
  url = "https://www.hobofoto.work/"